config/routes.rb
Rails.application.routes.draw do
 

  resources :products
  resources :product_features
  resources :pfeatures
  resources :country_of_origins
  mount RailsAdmin::Engine => '/radmin', as: 'rails_admin'
  resources :roles
  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  root "home#index"


  get 'home/index'

  get 'home/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  
  validates :name, presence: true, uniqueness: true 

  def to_s
    # show columns contents, not record object like: 	#<Vehicle:0x007f343b3f2890>	2016-06-08	
    # http://stackoverflow.com/questions/4829909/how-do-i-print-out-the-contents-of-an-object-in-rails-for-easy-debugging
    #"Name:#{self.name} Age:#{self.age} Weight: #{self.weight}"
    "#{name}"
  end

   
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
before_filter :authenticate_user!
  # before_action :set_role, only: [:show, :edit, :update, :destroy]

  #cancancan
  load_and_authorize_resource


  # cancancan..
  #load_and_authorize_resource :role

  # GET /roles
  def index
    @q = @roles.search params[:q]
    @roles = @q.result.page(params[:page])
  end

  # GET /roles/1
  def show
  end

  # GET /roles/new
  def new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  def create
    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: t('success_create') }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: t('success_update') }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: t('success_destroy') }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def role_params
    params.require(:role).permit(:name, :description, :active_status, :sort)
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @role.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h4>
      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
            <%= f.label :name, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :description, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :description, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :active_status, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.number_field :active_status, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :sort, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.number_field :sort, class: "form-control" %>
      </div>
        </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @role, class: "btn btn-info", :style=>'color:#FFFFFF;' %> &nbsp &nbsp &nbsp
<%= link_to 'Back', roles_path, class: "btn btn-default" %>

app/views/roles/index.html.erb
<row class="row is-table-row" >

  <div class="col-sm-1 ">
    <%= link_to 'Create', new_role_path , class: "btn btn-success"%>
  </div>

  <div class="col-sm-2 ">
    <h4>Listing Roles</h4>
  </div>

  <div class="col-sm-3">
    <%= search_form_for @q, class: 'search-form' do |f| %>
      <div class="input-group">
        <%= f.search_field :name_cont, class: 'form-control' %>
        <span class="input-group-btn">
          <button class="btn btn-primary">Search <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-sm-4 ">
    <%= paginate @roles %>
  </div>
  
  <div class="col-sm-2 ">
    <%= page_entries_info @roles, :entry_name => 'item' %>
  </div>
  
</row>


<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="1"></th>
            <th>Name</th>
      <th>Description</th>
      <th>Active status</th>
      <th>Sort</th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td>
          <div class="btn-group">
          <%= link_to 'Show', role, class: "btn btn-info", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Edit', edit_role_path(role), class: "btn btn-primary", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning", :style=>'color:#FFFFFF;' %>
          </div>
        </td>
        
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        <td><%= role.active_status %></td>
        <td><%= role.sort %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', roles_path, class: "btn btn-default" %>

app/views/roles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @role.active_status %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @role.sort %>
</p>

<br>
<%= link_to 'Edit', edit_role_path(@role), class: "btn btn-primary", :style=>'color:#FFFFFF;' %> &nbsp &nbsp
<%= link_to 'Back', roles_path, class: "btn btn-default" %>