config/routes.rb
Rails.application.routes.draw do
 

  resources :products
  resources :product_features
  resources :pfeatures
  resources :country_of_origins
  mount RailsAdmin::Engine => '/radmin', as: 'rails_admin'
  resources :roles
  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  root "home#index"


  get 'home/index'

  get 'home/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product_feature.rb
class ProductFeature < ApplicationRecord
  belongs_to :product
  belongs_to :pfeature
end

app/controllers/product_features_controller.rb
class ProductFeaturesController < ApplicationController
before_filter :authenticate_user!
  # before_action :set_product_feature, only: [:show, :edit, :update, :destroy]

  #cancancan
  load_and_authorize_resource


  # cancancan..
  #load_and_authorize_resource :product_feature

  # GET /product_features
  def index
    @q = @product_features.search params[:q]
    @product_features = @q.result.page(params[:page])
  end

  # GET /product_features/1
  def show
  end

  # GET /product_features/new
  def new
  end

  # GET /product_features/1/edit
  def edit
  end

  # POST /product_features
  def create
    respond_to do |format|
      if @product_feature.save
        format.html { redirect_to @product_feature, notice: t('success_create') }
        format.json { render :show, status: :created, location: @product_feature }
      else
        format.html { render :new }
        format.json { render json: @product_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_features/1
  def update
    respond_to do |format|
      if @product_feature.update(product_feature_params)
        format.html { redirect_to @product_feature, notice: t('success_update') }
        format.json { render :show, status: :ok, location: @product_feature }
      else
        format.html { render :edit }
        format.json { render json: @product_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_features/1
  def destroy
    @product_feature.destroy
    respond_to do |format|
      format.html { redirect_to product_features_url, notice: t('success_destroy') }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def product_feature_params
    params.require(:product_feature).permit(:name, :product_id, :pfeature_id, :active_status, :sort)
  end
end

app/helpers/product_features_helper.rb
module ProductFeaturesHelper
end

app/views/product_features/_form.html.erb
<%= form_for(@product_feature, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @product_feature.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@product_feature.errors.count, "error") %> prohibited this product_feature from being saved:</h4>
      <ul>
      <% @product_feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
            <%= f.label :name, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :product_id, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.collection_select :product_id, Product.all, :id, :name,  { prompt: true }, { :class => 'dgselect2' }  %>
        </div>
    </div>
  <div class="form-group">
            <%= f.label :pfeature_id, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.collection_select :pfeature_id, Pfeature.all, :id, :name,  { prompt: true }, { :class => 'dgselect2' }  %>
        </div>
    </div>
  <div class="form-group">
            <%= f.label :active_status, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.number_field :active_status, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :sort, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.number_field :sort, class: "form-control" %>
      </div>
        </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/product_features/edit.html.erb
<h1>Editing Product Feature</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @product_feature, class: "btn btn-info", :style=>'color:#FFFFFF;' %> &nbsp &nbsp &nbsp
<%= link_to 'Back', product_features_path, class: "btn btn-default" %>

app/views/product_features/index.html.erb
<row class="row is-table-row" >

  <div class="col-sm-1 ">
    <%= link_to 'Create', new_product_feature_path , class: "btn btn-success"%>
  </div>

  <div class="col-sm-2 ">
    <h4>Listing Product Features</h4>
  </div>

  <div class="col-sm-3">
    <%= search_form_for @q, class: 'search-form' do |f| %>
      <div class="input-group">
        <%= f.search_field :name_cont, class: 'form-control' %>
        <span class="input-group-btn">
          <button class="btn btn-primary">Search <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-sm-4 ">
    <%= paginate @product_features %>
  </div>
  
  <div class="col-sm-2 ">
    <%= page_entries_info @product_features, :entry_name => 'item' %>
  </div>
  
</row>


<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="1"></th>
            <th>Name</th>
      <th>Product</th>
      <th>Pfeature</th>
      <th>Active status</th>
      <th>Sort</th>
    </tr>
  </thead>

  <tbody>
    <% @product_features.each do |product_feature| %>
      <tr>
        <td>
          <div class="btn-group">
          <%= link_to 'Show', product_feature, class: "btn btn-info", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Edit', edit_product_feature_path(product_feature), class: "btn btn-primary", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Destroy', product_feature, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning", :style=>'color:#FFFFFF;' %>
          </div>
        </td>
        
        <td><%= product_feature.name %></td>
        <td><%= product_feature.product %></td>
        <td><%= product_feature.pfeature %></td>
        <td><%= product_feature.active_status %></td>
        <td><%= product_feature.sort %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/product_features/new.html.erb
<h1>New Product Feature</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', product_features_path, class: "btn btn-default" %>

app/views/product_features/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product_feature.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @product_feature.product %>
</p>

<p>
  <strong>Pfeature:</strong>
  <%= @product_feature.pfeature %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @product_feature.active_status %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @product_feature.sort %>
</p>

<br>
<%= link_to 'Edit', edit_product_feature_path(@product_feature), class: "btn btn-primary", :style=>'color:#FFFFFF;' %> &nbsp &nbsp
<%= link_to 'Back', product_features_path, class: "btn btn-default" %>